### ISSUE TITLE
[FEATURE] Add border or shadow to menu

### ISSUE THREAD

**Issue by pkptzx** [MirrorX-Desktop/MirrorX#16]
设置的弹出框应当增加边框或边框阴影.  
实在是让我眼晕.  
能否点击(任何,比如'域'这行)或鼠标out时消失.  

![image](https://user-images.githubusercontent.com/4339676/203160419-5b4c9e1b-d7c2-424b-9005-cf7871399d82.png)

**Comment by chenbaiyu0414** [comment]
Current menu element has conflict with tauri mouse drag area, and I will keep to find a solution.

**Comment by chenbaiyu0414** [comment]
Close because new ui layout had released.
