### ISSUE TITLE
Bottom link should be opened at browser

### ISSUE THREAD

**Issue by pkptzx** [MirrorX-Desktop/MirrorX#8]
界面最下部的MirrorX应当改为打开用户浏览器展示首页,这个应该是还未实现.  
导致在当前界面跳转,如果github无法访问,等到超时后才会展示该网页无法访问....    

![image](https://user-images.githubusercontent.com/4339676/203154519-ef0df25d-f3a7-448c-9c49-0c83f69b6c72.png)

![image](https://user-images.githubusercontent.com/4339676/203153876-0149e37d-83c8-430c-87a7-567a611fd2fd.png)

**Comment by chenbaiyu0414** [comment]
fixed at [347c14d](https://github.com/MirrorX-Desktop/MirrorX/commit/347c14dba95d3a5792999b748699b0be111fcd43)
